config/routes.rb
Rails.application.routes.draw do
  scope ENV['RAILS_RELATIVE_URL_ROOT'] || '/' do
    get ':site_id', to: 'extra_stops#extra_stops', as: 'extra_stops'
    match ':site_id/extra_stops', to: 'extra_stops#extra_stops', as: 'home', via: :all

    post ':site_id/collect_stops' => 'extra_stops#collect_stops', as: 'collect_stops'
    post ':site_id/add_stop', to: 'extra_stops#add_stop', as: 'add_stop'
    post ':site_id/update_stop', to: 'extra_stops#update_stop', as: 'update_stop'
    post ':site_id/clear_stops', to: 'extra_stops#clear_stops', as: 'clear_stops'
    post ':site_id/address_lookup', to: 'extra_stops#address_lookup', as: 'address_lookup'
    post ':site_id/send_data_to_parent', to: 'extra_stops#send_data_to_parent', as: 'send_data_to_parent'
  end
end

app/controllers/extra_stops_controller.rb
require 'json'
class ExtraStopsController < ApplicationController
  include ExtraStopsHelper
  before_filter :precache_tokens, except: 'index'
  before_filter :precache_locations

  def add_stop
    stop_params        = params[:stop]
    @index             = stop_params[:ExtraStop].to_i + 1
    re_hash_pickup_key = stop_params[:PickupKey].values.join
    stop_params.merge!(PickupKey: re_hash_pickup_key, ExtraStop: @index)
    @stop = get_location_details(stop_params)

    stop = render_to_string(
      partial: 'stop',
      object: @stop)
    render json: { stop: stop }
  end

  def address_lookup
    @addresses = AddressLookup.for(@site_id, Address: params[:address], City: params[:city],
                                             ZipCode: params[:zip], State: params[:state], AirportCode: @airport_code)

    if @addresses.empty?
      render json: { error: 'No locations were found.' }
    else
      addresses = render_to_string(
        partial: 'address_lookup_results',
        object: @addresses)
      render json: { addresses: addresses }

    end
  end

  def clear_stops
    @passenger_details = PassengerDetails.new(@site_id, [])
    render action: 'send_data_to_parent'
  end

  def collect_stops
    stops = params[:collected_stops]
    allStops = []
    stops.each do |stop|
      stop[1][:stop][:ExtraStop] = stop[1][:position]
      allStops << stop[1][:stop]
    end
    @passenger_details = PassengerDetails.new(@site_id, allStops)
    render json: { type: 'EXTRASTOPS', result: 0, data: @passenger_details.to_csv, sfx: @sfx, opt1: fields_list }
  end

  def extra_stops
    @index = 1
    @stop  = ExtraStop.new

    @locations = Locations.by_type(@site_id,
                                   airport_code: @airport_code, group_id: @group_alias,
                                   service_area: @service_area)

    @stops = puds unless params[:user_alias].blank?

    unless params[:formdata].blank? # Incoming extra stop CSV
      incoming_stops = PassengerDetails.from_csv(@site_id, params[:formdata]).stops

      @stops = []

      incoming_stops.each do |stop|
        @stops << get_form_data_details(stop)
      end
    end

  rescue HudsonWebService::ServiceError => e
    if e.to_s =~ /Invalid airport code/
      flash[:error] = 'Missing or invalid airport code parameter.'
      redirect_to action: 'error'
      return
    else
      raise
    end
  end

  def send_data_to_parent
    stops = params[:stop].values rescue []
    add_location_details(stops)
    logger.debug("stops are #{stops.inspect}")
    @passenger_details = PassengerDetails.new(@site_id, stops)
  end

  def update_stop
    stop_params        = params[:stop]
    @index             = stop_params[:ExtraStop].to_i + 1
    re_hash_pickup_key = stop_params[:PickupKey].values.join
    stop_params.merge!(PickupKey: re_hash_pickup_key, ExtraStop: @index)
    stop = get_location_details(stop_params)
    render json: { stop: stop }
  end

  private

  def address_lookup_type
    service = token('GEN_ADDRLISTSVC')
    service = 1 if service.blank?
    service.to_i == 1 ? :map_point : :afd
  end

  def first_stop?
    @stops.nil?
  end

  helper_method :first_stop?

  def incoming_stop?
    !params[:formdata].blank? || !puds.nil?
  end

  helper_method :incoming_stop?

  def get_form_data_details(stop)
    stop = stop.data

    loc = location_search_filter(stop)

    if loc.nil?
      address = AddressLookup.for(@site_id, Address: stop[:PickupAddr], City: stop[:PickupCity],
                                            ZipCode: stop[:PickupZip], State: '', AirportCode: @airport_code)

      address_post_key = address[0].post_key
      stop.merge!(PostKey: address_post_key, PickupLocation: stop[:PickupAddr])

    else
      stop.merge!(PickupLocation: loc.Location, PickupKey: loc.Code)
    end
  end

  def location_search_filter(stop)
    Locations.for(current_site_id,
                  airport_code: @airport_code,
                  group_id: @group_alias,
                  service_area: @service_area).find do |loc|
      if stop[:PickupLocation].blank?
        loc.Address == stop[:PickupAddr]
      else
        loc.Location == stop[:PickupLocation]
      end
    end
  end


  def get_location_details(stop)
# Rails.logger.debug "\nNew Stop: Before Processing\n#{stop.pretty_inspect}\n"
    if stop.is_a? PUD

      stop = { PickupLocation: stop.Location,
               PickupCity: stop.City,
               PickupState: stop.State,
               PickupZip: stop.Zip,
               PickupKey: stop.FareCode,
               PickupAddr: stop.Address,
               PUDDirections: stop.Directions }

    elsif address_lookup_type == :afd && !stop[:PostKey].blank?

      address = AddressLookup.details(@site_id, stop[:PostKey], @airport_code)
      stop.merge!(PickupLocation: address.template,
                  PickupCity: address.city,
                  PickupState: address.state,
                  PickupZip: address.zip_code,
                  PickupKey: address.fare_key,
                  PickupAddr: address.street)

    else

      # There's currently an optimiziation issue wiht Locations.for_key.
      # This is a quick fix until the issue can be fixed.
      loc = Locations.for(current_site_id,
                          airport_code: @airport_code,
                          group_id: @group_alias,
                          service_area: @service_area).find do |loc|
        loc.Code == stop[:PickupKey]
      end

      stop.merge!(PickupLocation: loc.Location,
                  PickupCity: loc.City,
                  PickupState: loc.State,
                  PickupZip: loc.Zip,
                  PickupKey: loc.Code,
                  PickupAddr: loc.Address)

      end
  # Rails.logger.debug "\nNew Stop: After Processing\n#{stop.pretty_inspect}\n"
  stop
   end

  def precache_locations
    loc = Locations.for(current_site_id,
                        airport_code: @airport_code,
                        group_id: @group_alias,
                        service_area: @service_area)
  end

  def precache_tokens
    Tokens.for(@site_id,
               %w(EXTRASTOPS_TERM CSSFONTCOLOR CSSBGCOLOR SEC_BG SEC_TEXT SUB_BG SUB_TEXT
                  PICKUPINFO_LOCTAB1 PICKUPINFO_LOCTAB2 PICKUPINFO_LOCCAPTIONS PICKUPZIPDESC
                  EXTRASTOPS_TERM), GroupAlias: @group_alias)
    Tokens.for(@site_id, %w(EXTRASTOPS_CAPTIONS EXTRASTOPS_DBNAMES PICKUPCITYDESC PICKUPHOTELDESC
                            PICKUPAIRPORTDESC PICKUPOTHERDESC PREFPICKUPDESC))
  end

  def puds
    unless @user_alias.blank?
      incoming_puds =  Profiles.puds(@site_id, @user_alias).dup.delete_if { |p| p.Airport.downcase != @airport_code.downcase }
      pud_stops = incoming_puds.collect { |pud| get_location_details(pud) }
      return pud_stops
    end
    nil
  end

  def token(name)
    Tokens.for(@site_id, name, GroupAlias: @group_alias)
  end

  def zip_label
    label = token('PICKUPZIPDESC')
    label = 'Zip Code' if label.blank?
    label
  end
end

app/helpers/extra_stops_helper.rb
module ExtraStopsHelper
  def address_lookup
    @content = content_tag(:div, class: 'form-group address-lookup') do
      concat content_tag(:label, 'Post Code')
      concat text_field_tag('zip', nil, name: 'stop[zip]',
                                        id: 'zip-input', class: 'zip-search stop form-control', data: { param: 'zip' })
      concat content_tag(:button, 'Find Address', type: 'button', class: 'address-lookup-btn btn btn-primary pull-left',
                                                  id: 'zip', data: { loading_text: 'Searching...' })
    end
    @content << content_tag(:div, class: 'form-group address-results') do
      concat content_tag(:label, 'Available Addresses', class: 'address-results')
      concat select_tag('address-results', '', name: 'stop[PostKey]', class: 'stop form-control address-select',
                                               id: 'address-results')
      concat link_to('Lookup Different Address', '#', class: 'new-search address-results', id: 'new-search')
    end
  end

  #               <%#= select_tag("address_results_#{form_id}",
  #                              available_addresses(@addresses),
  #                              :class => 'stop form-control location-select address_results_list',
  #                              :id => "address_results_select_#{form_id}",
  #                              :onchange => "setPostKey(#{form_id},
  #                                           $('address_results_select_'+#{form_id}).getValue());") %>

  def location_select_builder(locations)
    locations.map do |type|
      location_array = []
      location_type  = type[:label]
      type[:locations].each do |loc|
        location_array << [loc.Name, loc.Code]
      end
      content_tag(:div, class: 'form-group') do
        concat content_tag(:label, location_type.capitalize.html_safe, class: 'stop-label')
        concat select_tag "#{location_type.downcase}", options_for_select(location_array), include_blank: true,
                                                                                           name:  "[stop][PickupKey][loc_type_#{type[:type]}]", class: 'stop form-control location-select',
                                                                                           id:    "#{type[:type]}"
      end
    end.join("\n").html_safe
  end

  def field_builder(fields)
    fields.map do |field|
      next if skip_field?(field)
      content_tag(:div, class: 'form-group') do
        concat content_tag(:label, "#{field.caption}", class: 'stop-label')
        case field.field
        when /Passengers/
          concat select_tag('[stop][Passengers]',
                            options_for_select(0..59), include_blank: true ,
                                                       name: "[stop][#{field.field.capitalize}]", class: 'stop-info stop form-control', data: { param: 'Passengers' },
                                                       id: "#{field.caption.downcase}")
        when /PUDDirections/
          concat text_area_tag('[stop][PUDDirections]', nil, name: '[stop][PUDDirections]',
                                                             size: '30x5',
                                                             id: "#{field.caption.downcase}", class: 'stop-info stop form-control expand', data: { param: 'PUDDirections' }, style: 'margin-left:0')
        else
          concat text_field_tag("#{field.field.capitalize}", nil, name: "[stop][#{field.field.capitalize}]",
                                                                  id: "#{field.caption.downcase}", class: 'stop-info stop form-control', data: { param: "#{field.field.capitalize}" })
        end
      end
    end.join("\n").html_safe
  end

  def new_stop_button_content
    content = content_tag(:i, nil, class: ['fa', 'fa-plus-circle', 'fa-3x', 'pull-left'])
    content << content_tag(:h4, 'ADD ADDITIONAL STOP', class: 'list-group-item-heading')
    content << content_tag(:p, 'CLICK TO ADD MORE STOPS', class: 'list-group-item-text')
  end

  def stop_info(new_stop)
    content = content_tag(:div, nil, class: ['col-lg-2', 'no-padding', 'clearfix'])
    content << content_tag(:i, nil, class: ['fa', 'fa-plus-circle', 'fa-3x', 'pull-left'])
    content << content_tag(:h4, new_stop[:PickupLocation], class: 'list-group-item-heading')
    content << content_tag(:p, new_stop[:PickupAddr], class: 'list-group-item-text')
  end

  def address_label
    label = token('ROADDRESSDESC')
    label = 'Address' if label.blank?
    label.html_safe
  end

  def address_lookup_type
    service = token('GEN_ADDRLISTSVC')
    service = 1 if service.blank?
    service.to_i == 1 ? :map_point : :afd
  end

  def address_tab_label
    label = token('PICKUPINFO_LOCTAB2')
    label = 'Address' if label.blank?
    label.html_safe
  end

  # Attempts to return an appropriate form field given an extra stop field name.
  # For example, if given Passengers it would be correct to return a select list
  # whereas Name should be a text field. The default return value is a text field.
  def appropriate_field(field, stop, index)
    case field.field
    when /Passengers/
      select_tag('stop[' + index.to_s + '][' + field.field + ']',
                 options_for_select(0..59, stop.send(field.field).to_i))
    when /PUDDirections/
      text_area_tag('stop[' + index.to_s + '][' + field.field + ']',
                    stop.send(field.field), size: '30x5',
                                            class: 'text-area', style: 'margin-left:0')
    else
      text_field_tag('stop[' + index.to_s + '][' + field.field + ']',
                     stop.send(field.field), size: 30, class: 'text')
    end
  end

  def available_addresses(address_list)
    options = [['-- Select an address --', '']]

    if address_lookup_type == :afd
      address_list.each { |addr| options << [addr.template, addr.post_key] }
    else
      address_list.each do |addr|
        options << [
          "#{addr.street}, #{addr.city}, #{addr.state} #{addr.zip_code}",
          CGI.escape(Marshal.dump(addr))
        ]
      end
    end
    options_for_select(options)
  end

  def city_label
    label = token('CITYDESC')
    label = 'City' if label.blank?
    label.html_safe
  end

  def close_dialog?
    !@close_dialog.to_i.zero?
  end

  def display_address?
    displayed_address_fields.include? 'Address'
  end

  def display_city?
    displayed_address_fields.include? 'City'
  end

  def display_state?
    displayed_address_fields.include? 'State'
  end

  def display_zip?
    displayed_address_fields.include? 'ZipCode'
  end

  def displayed_address_fields
    fields = token('PICKUPINFO_LOCCAPTIONS').split(',')
    if fields.empty?
      fields = address_lookup_type == :afd ? %w(ZipCode) : %w(Address City State ZipCode)
    end
    fields
  end

  def display_address_lookup_tab?
    if @service_area.blank? && !@show_addrlu.nil?
      return @show_addrlu.to_i == 1

    else
      enabled       = token('MAPLOOKUP_ENABLED').to_i == 1
      service_areas = token('MAPLOOKUP_SERVICEAREAS').split(',').collect(&:to_i)

      enabled && service_areas.include?(@service_area.to_i)
    end
  end

  def fields
    ExtraStop.fields(@site_id)
  end

  def fields_list
    fields.collect(&:field).join(',')
  end

  def landmarks_tab_label
    label = token('PICKUPINFO_LOCTAB1')
    label = 'Landmarks' if label.blank?
    label.html_safe
  end

  def pud_label
    label = token('PREFPICKUPDESC')
    label = 'Preferred Locations' if label.blank?
    label.html_safe
  end

  def skip_field?(field)
    ['PickupAddr', 'PickupCity', 'PickupZip', 'PickupKey', 'PickupState', '', 'ExtraStop'].include?(field.field) ||
      field.caption.blank?
  end

  def state_label
    label = token('STATEDESC')
    label = 'State' if label.blank?
    label.html_safe
  end

  def zip_label
    label = token('PICKUPZIPDESC')
    label = 'Zip Code' if label.blank?
    label.html_safe
  end

  private

  def token(name)
    Tokens.for(@site_id, name, GroupAlias: @group_alias)
  end
end

app/views/extra_stops/forms/_add_stop_form.html.erb
<div class="modal fade" id="addStopModal" tabindex="-1" role="dialog" aria-labelledby="addStopModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!-- Alert Msg -->
      <!-- End Alert Msg -->
      <div class="modal-header hudson-secondary">
        <button type="button" class="close modal-close close-button" id='addStopModal-dismiss'>
        <i class="fa fa-times"></i></button>
        <h3 class="modal-title" id="addStopModalLabel"><%= first_stop? ?  first_stop_form_header : stop_form_header %></h3>
      </div>
      <div class="modal-info-box"></div>
      <div class="modal-body no-padding">
        <!--Form Start-->
        <div class="hudson-subsection" id="form-container">
          <!-- Tab panes -->
          <%= form_tag add_stop_path,
          before: 'if (!validateForm()) return false;',
          id:     "extra-stops-form", class: 'extra-stops-form', remote: true do %>
          <div class="form-inner">
            <div class="row">              <div class="col-xs-6 padding-10x5 pull-left" id="tab-container">
              <ul class="nav nav-tabs" id="extra-stop-nav-tabs" role="tablist">
                <li class="active">
                  <a href="#locations" role="tab" class="location-tab" id='loc' data-toggle="tab"><%= landmarks_tab_label %></a></li>

                  <% if display_address_lookup_tab? %>
                  <li>
                    <a href = "#enter-address" class = "address-tab" id='addr' role = "tab" data-toggle = "tab"><%= address_tab_label %></a>
                  </li>
                  <% end %>
                </ul>
              </div> </div>
              <div class="tab-content" id="extra-stop-tab-content">

                <div role="tabpanel" class="tab-pane active" id="locations">
                    <div class="col-xs-6 no-padding pull-left" id="loc-column">
                    <div class="extra-stop-well well" id="loc-well">
                      <!-- Location Selections-->
                      <%= location_select_builder(@locations) %>
                    </div>
                  </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="enter-address">
                  <div class="col-xs-6 no-padding pull-left" id="address-lookup-container">
                  <div class="extra-stop-well well" id="addr-well">
                    <%= render "extra_stops/forms/address_lookup" %>
                    <div id="display-address-results">
                    <div class="well well-lg" id="lookup-results"></div>
                    </div>
                    </div>

                  </div>
                </div>

              </div>
              <div class="col-xs-6 padding-10x5 pull-right" id='psgr-column'>
                <div class="hr-spacer"></div>
                <!-- Building Passenger Info Fields-->
                <%= field_builder(fields) %>
              </div>
            </div>
            <input id="stop-index" name="[stop]ExtraStop" type="hidden" value=""/>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn hudson-button close-button" id="form-close" data-dismiss="modal"><%= close_button_text %></button>
          <button type="button" class="btn cancel-button"><%= close_button_text %></button>
           <button type="button" class="btn action-button" data-stopId="" id="submit-stop-button"><%= first_stop? ?  submit_first_stop_button_text : submit_stop_button_text %></button>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/extra_stops/forms/_address_lookup.html.erb
<div class="form-group address-lookup" id="address-lookup-input-container">
  <label><%= post_code_label %></label>
  <input type="text" name="stop[zip]" id="zip-input" class="zip-search stop form-control">
  <button type="button" class="address-lookup-btn btn hudson-button pull-left" id="search-zip" data-loading-text="Searching..."><%= address_lookup_button_text %></button>
</div>
<div id="search-link-container">
  <a class="new-search address-results" id="new-search" href="#"><%= new_address_lookup_link_text %></a>
</div>